version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - .env               # ✅ Load environment variables into container

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend            # ✅ Wait for backend before starting
